$(function(){
	$(".top-img").click(function(){
		window.location.href="../index.html";
	});

    $(".index").click(function(){
        window.location.href="index.html";
    });
    $(".classify1").click(function(){
        window.location.href="html/classify1.html";
    });
    $(".img3").click(function(){
        window.location.href="html/register.html";
    });
    $(".food").click(function(){
        window.location.href="html/food.html";
    });
    $(".myself").click(function(){
        window.location.href="html/myself.html";
    });
});
